Repository bemusic/bemuse, pull requests merged in 2020-05, with the labels that each got.

#656 Updates usage of `co` to async function in src/packer.js
  packages/bemuse-tools/src/packer.js
Labels: category:Internals, to merge

#655 🐙 Migrate part of the code from `co` to `async function`s
  .gitpod.yml
  package.json
  packages/bemuse-notechart/src/index.ts
  packages/bemuse-tools/src/audio.js
  packages/bemuse-tools/src/bemuse-packer.js
  packages/bemuse-tools/src/packer.js
  src/auto-synchro/music/index.js
  src/coming-soon/demo/index.js
  src/devtools/playgrounds/skin.js
  src/game/display/player-display.js
  src/game/index.js
  src/scene-manager/index.js
  src/scintillator/index.spec.js
  src/scintillator/loader.js
  tasks/pre-deploy.js
  yarn.lock
Labels: c:ready, category:Internals

#653 Updates usage of to async function in src/devtools/playgrounds/skin.js #628
  src/devtools/playgrounds/skin.js
Labels: category:Internals, to merge

#648 Updates usage of `co` to async function in bemuse-packer.js
  packages/bemuse-tools/src/bemuse-packer.js
Labels: category:Internals, to merge

#662 Some input handling changes
  src/app/entities/Options.js
  src/app/game-launcher.ts
  src/app/options.js
  src/app/ui/OptionsInput.jsx
  src/app/ui/OptionsInput.scss
  src/game/input/dual-input.ts
  src/game/input/omni-input-plugin.js
  src/game/player.ts
  src/omni-input/axis-logic.ts
  src/omni-input/index.js
Labels: c:ready, category:New stuff

#663 feat(website): add DocSearch as recommended by docusaurus
  website/siteConfig.js
Labels: c:ready, category:Improvements

#666 Update docs on developing the website
  README.md
  docs/developer-guide.md
  package.json
Labels: c:ready, category:Internals

#671 Add web monetization meta tag.
  .circleci/config.yml
  .nvmrc
  bemuse/package.json
  bemuse/src/app/index.js
  package.json
  packages/monetizer/jest.config.js
  packages/monetizer/package.json
  packages/monetizer/src/index.test.ts
  packages/monetizer/src/index.ts
  packages/monetizer/tsconfig.json
  yarn.lock
Labels: c:ready, category:Internals
