Repository bemusic/bemuse, pull requests merged in 2022-10, with the labels that each got.

#751 fix: Fix to catch error from Promise
  bemuse/src/music-previewer/index.js
  bemuse/src/sampling-master/index.js
Labels: c:ready, category:Internals

#754 :pencil2: Fix docs badge link path
  README.md
Labels: c:ready, category:Internals

#758 Fixed high CPU usage when developing the project inside VS Code
  .vscode/settings.json
Labels: c:ready, category:Internals

#759 Update README.md
  README.md
Labels: c:ready, category:Internals

#762 Migrate builds from CircleCI to Github Actions
  .github/workflows/ci.yml
Labels: c:ready, category:Internals

#764 Refactor GitHub Actions workflows to use composite steps and add CI caching
  .github/actions/rush-cache/action.yml
  .github/actions/setup-project/action.yml
  .github/workflows/checks.yml
  .github/workflows/ci.yml
  .github/workflows/tidy.yml
  common/autoinstallers/bemuse-linter/dangerfile.ts
  packages/bms/package.json
Labels: c:ready, category:Internals

#752 fix: Fix minor bugs in HTML/CSS
  bemuse/src/app/ui/MusicInfoTabStats.scss
  bemuse/src/app/ui/OptionsCheckbox.scss
  bemuse/src/online/parse/cloud-code/public/index.html
Labels: c:ready, category:Internals

#766 Switch to Playwright for E2E testing
  .circleci/config.yml
  .github/workflows/ci.yml
  common/autoinstallers/bemuse-linter/dangerfile.ts
  common/config/rush/pnpm-lock.yaml
  e2e/.gitignore
  e2e/jsconfig.json
  e2e/package.json
  e2e/playwright.config.ts
  e2e/tests/Gameplay-test.js
  e2e/tests/gameplay.spec.ts
  e2e/tests/state.d.ts
  e2e/tsconfig.json
  e2e/yarn.lock
Labels: c:ready, category:Internals

#767 Added CODE_OF_CONDUCT.md and also updated README.md
  CODE_OF_CONDUCT.md
  README.md
Labels: c:ready, category:Internals

#749 :arrow_up: Avoid deprecated dependencies
  .circleci/config.yml
  bemuse/config/webpack.js
  bemuse/package.json
  bemuse/src/app/ui/MusicChartSelectorItem.jsx
  bemuse/src/app/ui/MusicInfoTabStats.jsx
  bemuse/src/app/ui/MusicInfoTabs.jsx
  bemuse/src/app/ui/Toolbar.jsx
  bemuse/src/audio-context/index.js
  bemuse/src/previewer/PreviewFileDropHandler.tsx
  bemuse/src/utils/query.js
  bemuse/tasks/build.js
  bemuse/tasks/support/dev-server/index.js
  common/config/rush/pnpm-lock.yaml
  packages/bemuse-indexer/package.json
  packages/bemuse-notechart/package.json
  packages/bemuse-tools/package.json
  packages/bms/package.json
  packages/monetizer/package.json
Labels: c:ready, category:Internals, hacktoberfest-accepted

#755 Convert updeep to immer (fixes #704)
  .vscode/settings.json
  bemuse/package.json
  bemuse/src/app/entities/LoadState.js
  bemuse/src/app/entities/MusicSearchText.js
  bemuse/src/app/entities/MusicSelection.js
  bemuse/src/app/entities/Options.js
  bemuse/src/music-collection/preprocessCollection.js
  common/config/rush/pnpm-lock.yaml
Labels: c:ready, category:Internals, hacktoberfest-accepted

#772 Remove `co` dependency
  bemuse/package.json
  bemuse/src/app/interactors/createCollectionLoader.spec.js
  bemuse/src/online/scoreboard-system/authenticationFlow.js
  bemuse/src/online/scoreboard-system/createScoreboardClient.js
  packages/bemuse-tools/package.json
  packages/bemuse-tools/src/indexer.js
Labels: c:ready, category:Internals, hacktoberfest-accepted

#775 Add Semgrep
  .github/actions/semgrep/action.yml
  .github/actions/semgrep/semgrep-problem-matcher.json
  .github/workflows/ci.yml
  .semgrep.yml
  .vscode/tasks.json
  bemuse/src/previewer/BarDot.tsx
  bemuse/src/previewer/PreviewCanvas.tsx
  bemuse/src/previewer/PreviewFileDropHandler.tsx
  bemuse/src/previewer/PreviewInfo.tsx
  bemuse/src/previewer/PreviewKeyHandler.tsx
  bemuse/src/ui/Button.tsx
  bemuse/src/ui/VBox.tsx
  bemuse/types/react.d.ts
Labels: c:ready, category:Internals

#776 Fix problem where sign-in is broken
  bemuse/src/online/scoreboard-system/createScoreboardClient.js
Labels: c:ready, category:Improvements

#778 Fix problem where project site cannot be accessed once Service Worker is installed
  bemuse/src/app/service-worker.js
  e2e/playwright.config.ts
  e2e/tests/gameplay.spec.ts
  e2e/tests/project-site.spec.ts
Labels: c:ready, category:Improvements
